source 'https://rubygems.org'
gem 'capybara', '~> 2.2.1'
gem 'selenium-webdriver', '~> 2.39'
gem 'site_prism', '~> 2.4'
gem 'rspec', '~> 2.12.0'
gem 'require_all', '~> 1.2.1'
gem 'ruby-progressbar', '~> 1.2.0'
gem 'yard'
gem 'nokogiri'
gem 'sauce', '~> 3.1.1'
gem 'activesupport'
gem 'i18n'
gem 'parallel_tests'
gem 'rspec-rails', '~> 2.12'